### ISSUE TITLE
能否支援段落加减的比对？

### ISSUE THREAD

**Issue by HackettLai** [YangguangZhou/FileDiff#2]
能否支援段落加减的比对？例如新增一行或者减少一行🙏🏻
![CleanShot 2024-05-10 at 14 50 09](https://github.com/YangguangZhou/FileDiff/assets/56993446/abe8b432-b8c5-4110-be38-9651ef61392c)

**Comment by YangguangZhou** [comment]
Now you can compare paragraph differences by https://diff.jerryz.com.cn 🥳
I assume you're not a native Chinese speaker?
