### ISSUE TITLE
[bug] 部分文本不能正确显示在输出框内

### ISSUE THREAD

**Issue by NailFec** [YangguangZhou/FileDiff#3]
本来想截图文本比对的结果的，但发现有代码没有正确显示。希望修复，orz

下图中，输出框（最右边的框）的第 `45` 行没有正确显示完整的代码。应为 `cout<<t[i].cod<<" ";` ，但是被错误地显示为了 `cout<` 。

尝试了以下方法，但 bug 仍然存在：

- [x] 刷新网页并重新输入
- [x] 在输入框内该行末尾添加其他字符并删去
- [x] 删去其他字符，只保留错误字符所在行
- [x] 使用其他浏览器

使用的浏览器：

- Google Chrome， 版本：` 127.0.6533.89（正式版本） （64 位）`
- Microsoft Edge，版本：`127.0.2651.86 (正式版本) (64 位)`

类似地，两个相同的 `#include<bits/stdc++.h` 也只显示为 `#include` ，可能是 `<` 字符的问题。但是代码中其他含有 `cout<<` 的字符却能够正确显示。

![image](https://github.com/user-attachments/assets/07294397-a19d-4243-90e4-1cd9b831f920)

![image](https://github.com/user-attachments/assets/dfc0533e-17b8-43d8-822c-ea7518d9b073)

**Comment by YangguangZhou** [comment]
已解决
